base/urls.py
from django.urls import path, include
from . import views
from base.views import FilteredPersonListView
from django.contrib.auth import views as auth_views #import this 



urlpatterns = [
  #  path('', views.allview, name="home"), 
    path("", FilteredPersonListView.as_view(),name="home"),
    path('about',views.about, name="about"),
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser  , name="logout"),
    path('register/', views.registerUser  , name="register"),
    path('fogot/', views.fogot, name="fogot"),
    path('profile/', views.profile, name="profile"),
    path('user-accounts',views.user_accounts,name="user-accounts"),
    path('edit-user/<str:pk>/',views.edit_user,name="edit-user"),
    path('change-password/', views.changepass, name="change-password"),
    path('newrecord/', views.newrecord  , name="newrecord"),
    path('editrecord/<str:pk>/', views.editrecord, name="editrecord"),
    path('approverecord/<str:pk>/', views.approverecord, name="approverecord"),
    path('export/', views.export_record, name='export'),
    path('export-user-record',views.export_record_user, name='export_record_user'),
    #path('accounts/', include('django.contrib.auth.urls')),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'), name='password_reset_complete'),      
    path("password_reset", views.password_reset_request, name="password_reset"),
    
      path('records/', views.allview, name="home")

]

zynga/urls.py
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('base.urls')),     
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

base/models.py
from email.policy import default
from statistics import mode
from django.db import models
from django.contrib.auth.models import AbstractUser
from simple_history.models import HistoricalRecords

class User(AbstractUser):
    user_type = models.BooleanField(default=False)
    avatar = models.ImageField(null=True,default='avatar.svg')
    history = HistoricalRecords()
    email = models.EmailField(unique=True)



class Plan_Type(models.Model):
    name = models.CharField(max_length=200)
    history = HistoricalRecords()

    def __str__(self):
        return self.name
   
class Functional_area(models.Model):
    name=models.CharField(max_length=30)
    history = HistoricalRecords()
    
    def __str__(self):
        return self.name    
    
class Investment_priority(models.Model):
    name=models.CharField(max_length=30)
    history = HistoricalRecords()
    
    def __str__(self):
        return self.name    

class Assets_Type(models.Model):
    name=models.CharField(max_length=30)
    history = HistoricalRecords()
    
    def __str__(self):
        return self.name    
    
class Capex_Type(models.Model):
    name=models.CharField(max_length=30)
    history = HistoricalRecords()
    
    def __str__(self):
        return self.name    
    
class Expected_Servince(models.Model):
    name=models.CharField(max_length=30)
    history = HistoricalRecords()
    
    def __str__(self):
        return self.name    
    
class Status(models.Model):
    name=models.CharField(max_length=20)
    history = HistoricalRecords()
    
    def __str__(self):
        return self.name    

class Approve_Status(models.Model):
    name=models.CharField(max_length=20)
    history = HistoricalRecords()
    
    def __str__(self):
        return self.name
    
class record(models.Model):
    record_id   = models.CharField(max_length=20,null=True) 
    company_code   = models.CharField(max_length=20,null=True) 
    functional_area =  models.ForeignKey(Functional_area, on_delete=models.SET_NULL,null=True)
    cost_center = models.CharField(max_length=50,null=True)
    plan_type = models.ForeignKey(Plan_Type, on_delete=models.SET_NULL,null=True)
    year = models.CharField(max_length=4,null=True)
    investment_priority = models.ForeignKey(Investment_priority, on_delete=models.SET_NULL,null=True)
    assets_type = models.ForeignKey(Assets_Type, on_delete=models.SET_NULL,null=True)
    capex_type = models.ForeignKey(Capex_Type, on_delete=models.SET_NULL,null=True)
    preview_number = models.CharField(max_length=20,null=True)
    asset_to_be_replace = models.CharField(max_length=20,null=True)
    expected_inverstment_value = models.DecimalField(decimal_places=3, max_digits=15,null=True)
    expected_servince_category = models.ForeignKey(Expected_Servince,on_delete=models.SET_NULL,null=True)
    expected_savings_value = models.CharField(max_length=20,null=True)
    project_start_date = models.DateField(null=True)
    project_end_date = models.DateField(null=True)
    status = models.ForeignKey(Status,on_delete=models.SET_NULL,null=True)    
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    create_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True ) 
    approve_time = models.DateTimeField(null=True)  
    approve_status = models.ForeignKey(Approve_Status, on_delete=models.SET_NULL, null=True)
    confirmation = models.BooleanField(default=False,null=False)
    history = HistoricalRecords()
    
    class Meta:
        ordering = ['-updated','-created']
        
    def __str__(self):
        return self.record_id

    

base/forms.py
from django.forms import ModelForm 
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from .models import record, User




class RecordForm(ModelForm):
    class Meta:
        model = record
        fields = '__all__'
        exclude = ['create_by','approve_time','approve_status','record_id']
      #  fields = ('record_id', 'company_code', 'functional_area_id')
      #  widgets = {
      #      'record_id': CharField(attrs={'class': 'form-control', 'placeholder': 'Record Id'}),
     #   }
class RecordApproveForm(ModelForm):
    class Meta:
        model = record
        fields = '__all__'
        exclude = ['create_by','approve_time']
     
class MyUserCreationForm(UserCreationForm):
    class Meta:
        model = User
       # fields = '__all__'
        fields = ['username', 'first_name','last_name','email','password1' ,'password2']

        
        
       
    
        
class userForm(PasswordChangeForm):
    class Meta:
        model = User
        fields = '__all__'
        
        
class UserChangeForm(UserChangeForm):
    class Meta:
        model = User
        
        fields = ['avatar', 'first_name','last_name','email']

class UserChangeFormAdmin(UserChangeForm):
    class Meta:
        model = User        
        fields = ['first_name','last_name','email','user_type']

base/views.py
import datetime
import csv
from django.http import HttpResponse
from django.shortcuts import render, redirect
#from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.contrib.auth import authenticate, login, logout 
from .models import record, User
from .forms import RecordForm,  MyUserCreationForm, userForm,UserChangeForm, RecordApproveForm,UserChangeFormAdmin
from .table import RecordTable, RecordTableAdmin,AdminUsers,PersonTable
from django.contrib.auth.forms import PasswordResetForm
from django.core.mail import send_mail, BadHeaderError
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes 
from .filters import RecordsFilter
#import django_tables2 as tables
from django_filters.views import FilterView
from django_tables2.views import SingleTableMixin
from django_tables2.export.views import ExportMixin  




def loginPage(request):
        page = 'login'
        if request.user.is_authenticated:
            return redirect('home')
        
        if request.method =='POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            
            try:
                user = User.objects.get(username=username)
            except:
                messages.error(request,'User Does not exist')     
                
            user = authenticate(request, username=username, password=password)
            
            if user is not None:
                login(request, user)
                return redirect('home')
            else:
                messages.error(request, 'Username or Password does not exits')
            
        context = {'page' : page}
        return render(request, 'base/login.html',context)

def logoutUser(request):
    logout(request)
    return redirect('home')

def registerUser(request): 
     form = MyUserCreationForm()
     
     if request.method =='POST':
         form = MyUserCreationForm(request.POST,request.FILES)
         if form.is_valid():
             user = form.save(commit=False)
             user.username = user.username.lower()
             user.save()
             login(request, user)
             return redirect('home')
         else: 
            messages.error(request, 'An error occured during registration')
   #  context = {'page' : page}
     return render(request, 'base/register.html',{'form' : form})

def fogot(request):
    
    return render(request,'base/fogot.html')

def about(request):
    return render(request,'base/about.html')

def profile(request):
    form = UserChangeForm(instance=request.user)
    if request.method == 'POST':
        form = UserChangeForm(request.POST,request.FILES,instance=request.user) 
        if form.is_valid():
            form.save()
            return redirect('home')
    
    return render(request, 'base/profile.html',{'form':form})

def changepass(request):
    form = userForm(request.user)
    if request.method == 'POST':
        form.userForm(request.POST)
        if form.is_valid:
            form.save()
            return redirect('home')
    return render(request,'base/change-password.html',{'form':form})
 
@login_required(login_url='login')
#def allview(AjaxDatatableView):
    # model = record
    # title = 'Permissions'
    # initial_order = [["record_id", "asc"], ]
    # length_menu = [[10, 20, 50, 100, -1], [10, 20, 50, 100, 'all']]
    # search_values_separator = '+'

    # column_defs = [
    #     AjaxDatatableView.render_row_tools_column_def(),
    #     {'name': 'record_id', 'visible': False, },
    #     {'name': 'company_code', 'visible': True, },
    #     {'name': 'year', 'visible': True, },
    #     {'name': 'cost_center', 'foreign_field': 'content_type__app_label', 'visible': True, },
    #     {'name': 'functional_area', 'foreign_field': 'content_type__model', 'visible': True, },
    # ]
def allview(request):    
    if request.user.user_type==True:
        
        try:
            table = RecordTableAdmin(record.objects.all())
            rfilter = RecordsFilter()
            table.paginate(page=request.GET.get("page", 1), per_page=20)
        except:
            table = None
            rfilter = RecordsFilter()     
            
        return render(request, "base/records.html", {
            "table": table,"rfilter":rfilter
        })
    else:
        try:
            table = RecordTable(record.objects.filter(create_by=request.user))
            table.paginate(page=request.GET.get("page", 1), per_page=20)
        except:
            table = None
        rfilter = RecordsFilter()     
        return render(request, "base/records.html", {
            "table": table,"rfilter":rfilter
        }) 

class FilteredPersonListView(ExportMixin, SingleTableMixin, FilterView):
    table_class = PersonTable
    model = record
    template_name = "template.html"

    filterset_class = RecordsFilter
        

@login_required(login_url='login')
def newrecord(request):
    form = RecordForm()
    
    if request.method=='POST':
        form = RecordForm(request.POST)
        
        if form.is_valid():            
            rc = form.save(commit=False)
            REC_ID = str(rc.cost_center)+str(rc.year)
            rc.create_by = request.user
            rc.record_id = str(rc.cost_center)+str(rc.year)
            rc.save()
         #   return  HttpResponse(record.objects.latest('id').id)
            ltid = record.objects.latest('id').id
            er = record.objects.get(id=ltid)
            er.record_id +=str(ltid)
            er.save()
            
            return redirect('home')
    context = {'form':form}
    return render(request, 'base/createRecord.html',context)

@login_required(login_url='login')
def editrecord(request, pk):
    er = record.objects.get(id=pk)
    form = RecordForm(instance=er)
    
    #if this is not the user that create the record
    if er.create_by !=  request.user :
        return HttpResponse('You are not allowed here')
    
    if request.method =='POST':
        form = RecordForm(request.POST, instance=er)
        if form.is_valid():
            form.save()
            return redirect('home')
            
    context = {'form':form,'record':er}
    return render(request, 'base/editRecord.html',context)

@login_required(login_url='login')
def approverecord(request, pk):
    er = record.objects.get(id=pk)
    form = RecordApproveForm(instance=er)

    if request.method =='POST':
        form = RecordApproveForm(request.POST, instance=er)
        if form.is_valid():
            form = form.save(commit=False)
            form.approve_time = datetime.datetime.now()
            form.save()
            return redirect('home')
            
    context = {'form':form}
    return render(request, 'base/approveRecord.html',context)

def export_record(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="record.csv"'

    writer = csv.writer(response)
    writer.writerow(['Record ID', 'Company Code', 'Functional Area', 'Cost Center','Plan Type','Year','Investment Priority','Assets Type','Capex Type','Preview Number','Asset to be Replace','Expected Inverstment Value','Expected Servince Category','Expected Savings Value','Project Start Date','Project End Date','Status','Confirmation','Approve Status'])
    users = record.objects.all()
    for user in users:
        writer.writerow([user.record_id,user.company_code, user.functional_area,user.cost_center,user.plan_type,user.year,user.investment_priority,user.assets_type, user.capex_type,user.preview_number,user.asset_to_be_replace,user.expected_inverstment_value,user.expected_servince_category,user.expected_savings_value,user.project_start_date,user.project_end_date,user.status,user.confirmation,user.approve_status])

    return response

def export_record_user(request):    
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="record.csv"'

    writer = csv.writer(response)
    writer.writerow(['Record ID', 'Company Code', 'Functional Area', 'Cost Center','Plan Type','Year','Investment Priority','Assets Type','Capex Type','Preview Number','Asset to be Replace','Expected Inverstment Value','Expected Servince Category','Expected Savings Value','Project Start Date','Project End Date','Status','Confirmation','Approve Status'])
    users = record.objects.filter(create_by=request.user)
    for user in users:
        writer.writerow([user.record_id,user.company_code, user.functional_area,user.cost_center,user.plan_type,user.year,user.investment_priority,user.assets_type, user.capex_type,user.preview_number,user.asset_to_be_replace,user.expected_inverstment_value,user.expected_servince_category,user.expected_savings_value,user.project_start_date,user.project_end_date,user.status,user.confirmation,user.approve_status])

    return response

def user_accounts(request):
 
   # table = User.objects.all()
    table = User.objects.all()
  #  print(vars(table))
  #  table.paginate(page=request.GET.get("page", 1), per_page=20)
    return render(request, "base/users.html", { "table": table })  

def edit_user(request, pk):
    er = User.objects.get(id=pk)
    form = UserChangeFormAdmin(instance=er) 
    
    if request.method == 'POST':
        form.UserChangeFormAdmin(request.POST, instance=er)
        if form.is_valid:
            form.save()
            return redirect('user-accounts')
    return render(request,'base/admin-change-user.html',{'form':form}) 


def password_reset_request(request):
    password_reset_form = PasswordResetForm()
    message = ''
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():

base/templates/base/createRecord.html
{% extends 'main.html' %}

{% block  content%}   
<div class=" offset-1 col-10 ">
    <div class="container-fluid">
        <div class="row mb-2">
        <div class="col-sm-6">
            <h1>Record</h1>
        </div>
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
            <li class="breadcrumb-item "><a href="{% url 'home' %}">Record</a></li>
            <li class="breadcrumb-item active">New Record</li>
            </ol>
        </div>
        </div>
    </div><!-- /.container-fluid -->
</div>
</section>
<div class="content"> 
<div class="row">
  {% if form.errors %}
    <div class="alert alert-danger">
        {{ form.errors }}
    </div>
  {% endif %}
    <div class=" offset-1 col-10 ">
        <div class="card">
          <div class="card-header    text-center">
          <div class="col-sm-12">   <h3 class="h5">Create New Record</h3>
          </div>
            
          </div>
          <!-- /.card-header -->
          <form class="form-horizontal" method="post" enctype="multipart/form-data">
              {% csrf_token %}   
            <div class="card-body">
              <div class="form-group row">
                <label for="id_record_id" class="col-sm-3 col-form-label">Record Id</label>                
                <div class="col-sm-9">
                   <input type="text" disabled placeholder="Automaticaly Genarated" />       
                </div>
              </div>
              <div class="form-group row">
                <label for="id_company_code" class="col-sm-3 col-form-label">Company Code <sup>*</sup></label>
                <div class="col-sm-9"> 
                  {{ form.company_code }}
                </div>
              </div>
              <div class="form-group row">
                <label for="id_functional_area" class="col-sm-3 col-form-label">Functional Area</label>
                <div class="col-sm-9"> 
              {{ form.functional_area }}
 
                </div>
              </div>
              <div class="form-group row">
                <label for="id_cost_center" class="col-sm-3 col-form-label">Cost Center</label>
                <div class="col-sm-9"> 
                  {{ form.cost_center }} 
                </div>
              </div>

              <div class="form-group row">
                <label for="id_plan_type" class="col-sm-3 col-form-label">Plan type</label>
                <div class="col-sm-9">
                  {{ form.plan_type }} 
                </div>
              </div>

              <div class="form-group row">
                <label for="id_year" class="col-sm-3 col-form-label">Year</label>
                <div class="col-sm-9">
                  {{ form.year }}  
                </div>
              </div> 

              <div class="form-group row">
                <label for="id_investment_priority" class="col-sm-3 col-form-label">Investment prioritization</label>
                <div class="col-sm-9"> 
                  {{ form.investment_priority }} 
                </div>
              </div> 

              <div class="form-group row">
                <label for="id_assets_type" class="col-sm-3 col-form-label">Asset type</label>
                <div class="col-sm-9">
                  {{ form.assets_type }} 
                </div>
              </div> 

              <div class="form-group row">
                <label for="id_capex_type" class="col-sm-3 col-form-label">Capex Type</label>
                <div class="col-sm-9">
                  {{ form.capex_type }} 
                </div>
              </div> 

              <div class="form-group row">
                <label for="id_preview_number" class="col-sm-3 col-form-label">Preview Number</label>
                <div class="col-sm-9">
                  {{ form.preview_number }}  
                </div>
              </div> 

              <div class="form-group row">
                <label for="id_asset_to_be_replace" class="col-sm-3 col-form-label">Asset to be replaced (SAP Number)</label>
                <div class="col-sm-9">
                  {{ form.asset_to_be_replace }}  
                </div>
              </div> 

              <div class="form-group row">
                <label for="id_expected_inverstment_value" class="col-sm-3 col-form-label">Expected Investment Value, EUR</label>
                <div class="col-sm-3">
                  {{ form.expected_inverstment_value }}  
                </div>
              </div> 

              <div class="form-group row">
                <label for="id_expected_servince_category" class="col-sm-3 col-form-label">Expected Savings Category</label>
                <div class="col-sm-9">
                  {{ form.expected_servince_category }} 
                </div>
              </div> 

              <div class="form-group row">
                <label for="id_expected_savings_value" class="col-sm-3 col-form-label">Expected Savings Value, EUR</label>
                <div class="col-sm-9">
                  {{ form.expected_savings_value }}  
                </div>
              </div> 

              <div class="form-group row">
                <label for="id_project_start_date" class="col-sm-3 col-form-label">Project Start Date</label>
                <div class="col-sm-2">
                  {{ form.project_start_date }}  
                </div>
              </div> 

              <div class="form-group row">
                <label for="id_project_end_date" class="col-sm-3 col-form-label">Project End Date</label>
                <div class="col-sm-2">
                  {{ form.project_end_date }}  
                </div>
              </div> 

              <div class="form-group row">
                <label for="id_status" class="col-sm-3 col-form-label">Status</label>
                <div class="col-sm-9">
                  {{ form.status }}
                </div>
              </div>

              <div class="row">
                        <div class=" offset-3 col-8">
                            <div class="icheck-primary">
                                {{  form.confirmation }}
                                <label for="id_confirmation">
                                I hereby declare that the provided above information is correct*
                                </label>
                            </div>
                        </div>
</div>

            </div>
            <!-- /.card-body -->
            <div class="card-footer text-center">
              <a  href="{% url 'home' %}" class="btn btn-default btn-sm col-sm-2"> Cancel </a>
              <button type="submit" class="btn btn-primary btn-sm col-sm-2"> Send for approval </button>
              
            </div>
            <!-- /.card-footer -->
          </form>
        </div>
        <!-- /.card -->
      </div>
    
</div> 
{% endblock content %}

{% block extrscripst %}
<script>
    var from_fields = document.getElementsByTagName('input') 
    from_fields[1].placeholder = "AB7E.XXXXX2022n";
    from_fields[2].placeholder = "AB7E";
    from_fields[3].placeholder = " AB7E.XXXXX";
    from_fields[4].placeholder = "YYYY";
    from_fields[5].placeholder = "15002018";
    from_fields[6].placeholder="15002018";
    from_fields[7].placeholder="123456789";
    from_fields[8].placeholder="123456789";

    for (field in from_fields){
     // from_fields[field].className +=' text'; 
    }

</script>
{% endblock extrscripst%}

base/templates/base/editRecord.html
{% extends 'main.html' %}

{% block  content%}   
<div class=" offset-1 col-10 ">
    <div class="container-fluid">
        <div class="row mb-2">
        <div class="col-sm-6">
            <h1>Record</h1>
        </div>
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
            <li class="breadcrumb-item "><a href="{% url 'home' %}">Record</a></li>
            <li class="breadcrumb-item active">Edit Record</li>
            </ol>
        </div>
        </div>
    </div><!-- /.container-fluid -->
</div>
</section>
<div class="content"> 
<div class="row">
  {% if form.errors %}
    <div class="alert alert-danger">
        {{ form.errors }}
    </div>
  {% endif %}
    <div class=" offset-1 col-10 ">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Create New Record</h3>

            <div class="card-tools">
              <div class="input-group input-group-sm" style="width: 150px;">
                  
              </div>
            </div>
          </div>
          <!-- /.card-header -->
          <form class="form-horizontal" method="post" enctype="multipart/form-data">
              {% csrf_token %}   
            <div class="card-body">
              <div class="form-group row">
                <label for="id_record_id" class="col-sm-3 col-form-label">Record Id</label>                
                <div class="col-sm-9">
                    {{ record.record_id }}             
                </div>
              </div>
              <div class="form-group row">
                <label for="id_company_code" class="col-sm-3 col-form-label">Company Code <sup>*</sup></label>
                <div class="col-sm-9"> 
                  {{ form.company_code }}
                </div>
              </div>
              <div class="form-group row">
                <label for="id_functional_area" class="col-sm-3 col-form-label">Functional Area</label>
                <div class="col-sm-9"> 
              {{ form.functional_area }}
 
                </div>
              </div>
              <div class="form-group row">
                <label for="id_cost_center" class="col-sm-3 col-form-label">Cost Center</label>
                <div class="col-sm-9"> 
                  {{ form.cost_center }} 
                </div>
              </div>

              <div class="form-group row">
                <label for="id_plan_type" class="col-sm-3 col-form-label">Plan type</label>
                <div class="col-sm-9">
                  {{ form.plan_type }} 
                </div>
              </div>

              <div class="form-group row">
                <label for="id_year" class="col-sm-3 col-form-label">Year</label>
                <div class="col-sm-9">
                  {{ form.year }}  
                </div>
              </div> 

              <div class="form-group row">
                <label for="id_investment_priority" class="col-sm-3 col-form-label">Investment prioritization</label>
                <div class="col-sm-9"> 
                  {{ form.investment_priority }} 
                </div>
              </div> 

              <div class="form-group row">
                <label for="id_assets_type" class="col-sm-3 col-form-label">Asset type</label>
                <div class="col-sm-9">
                  {{ form.assets_type }} 
                </div>
              </div> 

              <div class="form-group row">
                <label for="id_capex_type" class="col-sm-3 col-form-label">Capex Type</label>
                <div class="col-sm-9">
                  {{ form.capex_type }} 
                </div>
              </div> 

              <div class="form-group row">
                <label for="id_preview_number" class="col-sm-3 col-form-label">Preview Number</label>
                <div class="col-sm-9">
                  {{ form.preview_number }}  
                </div>
              </div> 

              <div class="form-group row">
                <label for="id_asset_to_be_replace" class="col-sm-3 col-form-label">Asset to be replaced (SAP Number)</label>
                <div class="col-sm-9">
                  {{ form.asset_to_be_replace }}  
                </div>
              </div> 

              <div class="form-group row">
                <label for="id_expected_inverstment_value" class="col-sm-3 col-form-label">Expected Investment Value, EUR</label>
                <div class="col-sm-3">
                  {{ form.expected_inverstment_value }}  
                </div>
              </div> 

              <div class="form-group row">
                <label for="id_expected_servince_category" class="col-sm-3 col-form-label">Expected Savings Category</label>
                <div class="col-sm-9">
                  {{ form.expected_servince_category }} 
                </div>
              </div> 

              <div class="form-group row">
                <label for="id_expected_savings_value" class="col-sm-3 col-form-label">Expected Savings Value, EUR</label>
                <div class="col-sm-9">
                  {{ form.expected_savings_value }}  
                </div>
              </div> 

              <div class="form-group row">
                <label for="id_project_start_date" class="col-sm-3 col-form-label">Project Start Date</label>
                <div class="col-sm-2">
                  {{ form.project_start_date }}  
                </div>
              </div> 

              <div class="form-group row">
                <label for="id_project_end_date" class="col-sm-3 col-form-label">Project End Date</label>
                <div class="col-sm-2">
                  {{ form.project_end_date }}  
                </div>
              </div> 

              <div class="form-group row">
                <label for="id_status" class="col-sm-3 col-form-label">Status</label>
                <div class="col-sm-9">
                  {{ form.status }}
                </div>
              </div>

              <div class="row">
                        <div class=" offset-3 col-8">
                            <div class="icheck-primary">
                                {{  form.confirmation }}
                                <label for="id_confirmation">
                                I hereby declare that the provided above information is correct*
                                </label>
                            </div>
                        </div>
              </div>

            </div>
            <!-- /.card-body -->
            <div class="card-footer text-center">
              <a href="{% url 'home' %}" class="btn btn-default btn-sm col-sm-2">Cancel</a>
              <button type="submit" class="btn btn-primary btn-sm col-sm-2">Save</button>
              
            </div>
            <!-- /.card-footer -->
          </form> 
        </div>
        <!-- /.card -->
      </div>
    
</div>

{% endblock content %}